import "./globals.css";
import React, { ReactNode } from "react";
import type { Metadata } from "next";
import ReactQuery from "../components/ReactQuery";
import NextAuthProvider from "@/components/NextAuthProvider";
import { Session } from "next-auth";
interface NextAuthProps {
  children: ReactNode;
  session: Session | null | undefined;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }: NextAuthProps) {
  return (
    <html lang="en">
      <body className={"px-5 w-screen h-screen overflow-hidden"}>
        <NextAuthProvider session={session}>
          <ReactQuery>{children}</ReactQuery>
        </NextAuthProvider>
      </body>
    </html>
  );
}